# Generated by Django 5.1.2 on 2024-11-11 16:11

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContentCreator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Descripción')),
                ('content_type', models.CharField(default='Contenido general', max_length=60)),
                ('subtitle', models.CharField(default='Nova WoW', max_length=60)),
                ('youtube_video_url', models.URLField(blank=True, max_length=300, null=True)),
                ('avatar_image_url', models.URLField(blank=True, max_length=300, null=True)),
                ('youtube_channel_url', models.URLField(blank=True, max_length=300, null=True)),
                ('facebook_page_url', models.URLField(blank=True, max_length=300, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DownloadClientPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Descarga del cliente', max_length=255)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Contenido')),
                ('mac_instructions', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Instrucciones para macOS')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Contenido')),
                ('fecha_publicacion', models.DateTimeField(auto_now=True)),
                ('fecha_fin_evento', models.DateField(blank=True, null=True)),
                ('enlace', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecruitAFriend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Recluta a un amigo', max_length=255)),
                ('information', models.CharField(default='Información', max_length=255)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Contenido')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecruitReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_friends', models.IntegerField()),
                ('reward_name', models.CharField(max_length=100)),
                ('item_id', models.IntegerField()),
                ('item_quantity', models.IntegerField(default=1)),
                ('item_link', models.URLField()),
                ('icon_class', models.CharField(help_text="Clase CSS para el icono (ej. 'icontinyl q3')", max_length=50)),
                ('claimed_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServerSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
                ('gamebuild', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClaimedReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField()),
                ('character_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('recruit_reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claimed_rewards', to='home.recruitreward')),
            ],
        ),
        migrations.CreateModel(
            name='SistemaOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('url_descarga', models.URLField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sistemas_operativos', to='home.clientecategoria')),
            ],
        ),
    ]
