# Generated by Django 5.1.2 on 2024-11-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_accountactivation_remove_recruitreward_claimed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountactivation',
            name='salt',
            field=models.CharField(max_length=128),
        ),
    ]
